### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by hikobend** [hikobend/ec2_cicd_test#1]
- [x] nginx puma Docker化
- [x] pushしてrails,nginxをECRに保存
- [x] EC2にデプロイするcompose.ymlを作成
- [x] EC2にcompose.ymlを保存
- [ ] 手動デプロイ
- [ ] DB接続
- [ ] react
